### ISSUE TITLE
什么时候开源

### ISSUE THREAD

**Issue by Lxg-233** [InvertedForest/SynSP#2]
佬，什么时候开源

**Comment by InvertedForest** [comment]
最近尝试为小模型添加了外置的大知识库https://github.com/InvertedForest/SynSP2，效果还不错，这个的开源最近有空再搞。: )
I recently experimented with enhancing a small model by incorporating a large external knowledge base, and the results were quite impressive. The open-source project I used is called SynSP2, and it can be found on GitHub: <https://github.com/InvertedForest/SynSP2>. I plan to continue working on SynSP when I have some free time : )
